// Types authContext
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
export const ACTCONTRA_EXITOSO = "ACTCONTRA_EXITOSO";
export const ACTCONTRA_ERROR = "ACTCONTRA_ERROR";
export const OCULTAR_MENSAJE = "OCULTAR_MENSAJE";
export const OCULTAR_MENSAJE_COD = "OCULTAR_MENSAJE_COD";
export const RECARGANDO_PAGINA = "RECARGANDO_PAGINA";

// Types de alertas
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
export const LISTA_USUARIOS = "LISTA_USUARIOS";
export const OBTENER_USUARIO_ERROR = "OBTENER_USUARIO_ERROR";

//TYPES DE TRAMITES
export const EXITO_REGISTARTRAMITE = "EXITO_REGISTARTRAMITE";
export const ERROR_REGISTARTRAMITE = "ERROR_REGISTARTRAMITE";
export const EXITO_SUBIRARCHIVO = "EXITO_SUBIRARCHIVO";
export const ERROR_SUBIRARCHIVO = "ERROR_SUBIRARCHIVO";
export const EXITO_BUSCARPORCOD = "EXITO_BUSCARPORCOD";
export const ERROR_BUSCARPORCOD = "ERROR_BUSCARPORCOD";
export const EXITO_LISTARTRAMITES = "EXITO_LISTARTRAMITES";
export const ERROR_LISTARTRAMITES = "ERROR_LISTARTRAMITES";
export const EXITO_LISTARTRAMITEUSUARIO = "EXITO_LISTARTRAMITEUSUARIO";
export const ERROR_LISTARTRAMITEUSUARIO = "ERROR_LISTARTRAMITEUSUARIO";
export const EXITO_ACEPTARTRAMITES = "EXITO_ACEPTARTRAMITES";
export const ERROR_ACEPTARTRAMITES = "ERROR_ACEPTARTRAMITES";
export const EXITO_LISTARTRAMITEACEPTADO = "EXITO_LISTARTRAMITEACEPTADO";
export const ERROR_LISTARTRAMITEACEPTADO = "ERROR_LISTARTRAMITEACEPTADO";
export const EXITO_DERIVARTRAMITES = "EXITO_DERIVARTRAMITES";
export const ERROR_DERIVARTRAMITES = "ERROR_DERIVARTRAMITES";
export const EXITO_ELIMINAR = "EXITO_ELIMINAR";
export const ERROR_ELIMINAR = "ERROR_ELIMINAR";
